language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files
        - $HOME/.npm

php:
    - 7.0
    - 7.1

env:
    global:
        - SYMFONY_ENV=test

branches:
    except:
        - /^analysis-.*$/

matrix:
    allow_failures:
        - hhvm
    fast_finish: true
    allow_failures:
        - php: 7.1
    include:
        - php: 7.0
          env: COVERAGE=true

before_install:
    - . $HOME/.nvm/nvm.sh
    - nvm install 6
    - nvm use 6
    - npm install -g bower gulp-cli
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - mysql -e 'create database symfony;'

install:
    - make COMPOSEROPTS="--prefer-dist --no-interaction" deps

before_script:
    - make setup
    - make GULPOPTS="--env production" frontend

script:
    - make test

services:
    - mysql
