framework:
    translator: { fallback: "%locale%" }

# Doctrine cache providers
doctrine_cache:
    providers:
        phpcr_meta:
            type: "%phpcr_cache%"
        phpcr_nodes:
            type: "%phpcr_cache%"

# MassiveSearch Configuration
massive_search:
    adapters:
        zend_lucene:
            basepath: "%kernel.var_dir%/indexes"

# JMS Serializer Configuration
jms_serializer:
    metadata:
        debug: "%kernel.debug%"

# SuluCore Configuration
sulu_core:
    webspace:
        config_dir: "%kernel.root_dir%/Resources/webspaces"
    content:
        structure:
            default_type:
                snippet: "default"
            paths:
                homepage:
                    path: "%kernel.root_dir%/Resources/templates/pages"
                    type: "home"
                page:
                    path: "%kernel.root_dir%/Resources/templates/pages"
                    type: "page"
                snippet:
                    path: "%kernel.root_dir%/Resources/templates/snippets"
                    type: "snippet"

# SuluDocumentManager Configuration
sulu_document_manager:
    sessions:
        default:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"
        live:
            backend: "%phpcr_backend%"
            workspace: "%phpcr_workspace%_live"
            username: "%phpcr_user%"
            password: "%phpcr_pass%"

# SuluWebsocket Configuration
sulu_websocket:
    server:
        http_host: "%websocket_url%"
        port: "%websocket_port%"

# SuluHttpCache Configuration
sulu_http_cache:
    handlers:
        debug:
            enabled: "%kernel.debug%"

# SuluMedia Configuration
sulu_media:
    storage:
        local:
            path: "%kernel.var_dir%/uploads/media"

dubture_f_fmpeg:
    ffmpeg_binary: /usr/local/bin/ffmpeg # path to ffmpeg
    ffprobe_binary: /usr/local/bin/ffprobe # path to ffprobe
    binary_timeout: 300 # Use 0 for infinite
    threads_count: 4

# Just a dirty hack to get the jms serializer bundle correctly working
# https://github.com/schmittjoh/JMSSerializerBundle/pull/270#issuecomment-21171800
services:
    jms_serializer.cache_naming_strategy: "@sulu_core.serialize_caching_strategy"
