sulu_tag:
    resource: "@SuluTagBundle/Resources/config/routing.yml"
    prefix:   /tag

sulu_tag_api:
    resource: "@SuluTagBundle/Resources/config/routing_api.yml"
    prefix:   /api

sulu_admin:
    resource: "@SuluAdminBundle/Resources/config/routing.yml"
    prefix:

sulu_contact:
    resource: "@SuluContactBundle/Resources/config/routing.yml"
    prefix: /contact

sulu_contact_api:
    type: rest
    resource: "@SuluContactBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_security:
    resource: "@SuluSecurityBundle/Resources/config/routing.xml"
    prefix: /security

sulu_security_api:
    type: rest
    resource: "@SuluSecurityBundle/Resources/config/routing_api.xml"
    prefix: /api

sulu_content:
    resource: "@SuluContentBundle/Resources/config/routing.yml"
    prefix: /content

sulu_content_api:
    type: rest
    resource: "@SuluContentBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_media:
    resource: "@SuluMediaBundle/Resources/config/routing.yml"
    prefix: /media

sulu_media_website:
    resource: "@SuluMediaBundle/Resources/config/routing_website.yml"

sulu_media_api:
    type: rest
    resource: "@SuluMediaBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_category:
    resource: "@SuluCategoryBundle/Resources/config/routing.yml"
    prefix: /category

sulu_category_api:
    resource: "@SuluCategoryBundle/Resources/config/routing_api.yml"
    prefix: /api

sulu_snippet_api:
    resource: "@SuluSnippetBundle/Resources/config/routing_api.yml"
    type: rest
    prefix: /api

sulu_location:
    resource: "@SuluLocationBundle/Resources/config/routing.yml"
    prefix: /location

sulu_website:
    resource: "@SuluWebsiteBundle/Resources/config/routing.yml"
    prefix: /website

sulu_website_api:
    resource: "@SuluWebsiteBundle/Resources/config/routing_api.yml"
    type: rest
    prefix: /api

sulu_websocket:
    type: rest
    resource: "@SuluWebsocketBundle/Resources/config/routing.yml"
    prefix: /websocket

sulu_core:
    type: rest
    resource: "@SuluCoreBundle/Resources/config/routing_api.xml"
    prefix: /api

sulu_search:
    resource: "@SuluSearchBundle/Resources/config/routing.yml"
    prefix: /search
